### PR TITLE
Added support for 3.0.0 version

### PR DESCRIPTION
**Pull request by brunolau**
This changeset adds support for the L2DB 3.0.0 version, while keeping backwards compatibility with the 2.x.x version

### CODE REVIEW

**Comment by sdanyliv** [comment]
Thanks, for this PR! Really appreciate.
We have found problems between two versions easily. But we decided to simplify your fix with just removing obsolete functions usage and defining new SqlServer provider by simple hack. Hack will be removed after 3.0 release and library will be pointed to newer version.

Please check for latest changes in master branch how it work in your case. 
Thanks!

**Comment by brunolau** [comment]
Works for my case, thanks. 

Just one note - in LinqToDBForEFToolsImplDefault starting at line 306, code kicks in when the connectionString is empty [not sure when this might happen in real life scenario thou]. But I assume that line 324 would return SqlServerDataProvider using the "System.Data.SqlClient" provider, which might not be desirable

**Comment by sdanyliv** [comment]
It should work in almost all cases. For version linq2db 3.0-preview2, we will change default provider to `SqlServerProvider.MicrosoftDataSqlClient`

**Comment by brunolau** [comment]
Any chance to pull the changes on nuget release? [at least some preview version or so]

**Comment by sdanyliv** [comment]
Moment, I'll do it right now.

**Comment by sdanyliv** [comment]
Superseded  by 597fca804114cb1eb95049b726656b313cb0e493
Released in 2.0.5

**Pull request closed without merging**
